POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "email": "katirin90@gmail.com",
    "password": "katirin",
    "role": "DRIVER"
}
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "email": "katirin_shipper@gmail.com",
    "password": "katirin",
    "role": "SHIPPER"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "katirin_shipper@gmail.com",
    "password": "katirin"
}

###
POST http://localhost:8080/api/auth/forgot_password
Content-Type: application/json

{
    "email": "katirin90@gmail.com"
}

###
GET http://localhost:8080/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE0NDc2NDR9.MZVKg_U0ozuZTv8G0nVKLTPcZ9TABRYNAY7W50Rjyao

###
PATCH http://localhost:8080/api/users/me/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjEyNjEzMDd9.ntsNW758iCgRKCG6_mFR22KtayKzMicK5cWmFj1Idps

{
  "oldPassword": "katirin",
  "newPassword": "11111"
}

###
POST http://localhost:8080/api/users/me/upload_photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDhlMmY5MWEyYjRhN2ZlNjM1MDIwNiIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE3Nzk5OTV9.3eRKb4Y-Jq_bhvZQRK4OEylGNB6KT3Anh6eT6T--8v0


###
DELETE http://localhost:8080/api/users/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDI4MDQxYWVlMWRmM2JhNmQ3NjJkNyIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjExNjk0NzV9.UnE88rSekhNQRJSg3qqdaxtyva9eL1ZAbj4bOwXSre0

###
GET http://localhost:8080/api/trucks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE1MjA5MTZ9.BBfSCr1aCcgLR-k-n9hTSnvF9I5E0xRVE-gZGMBNtUE

###
POST http://localhost:8080/api/trucks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDhlMmY5MWEyYjRhN2ZlNjM1MDIwNiIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE5MzQ1OTB9.yyo4xrNMcb9Z4JxDt1OcICD3jt82kGlbvFDTHHN071Y

{
  "type": "SPRINTER"
}

###
POST http://localhost:8080/api/trucks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE1MjA5MTZ9.BBfSCr1aCcgLR-k-n9hTSnvF9I5E0xRVE-gZGMBNtUE

{
  "type": "SPRINTER"
}

###
GET http://localhost:8080/api/trucks/6305fd837576a8e791b0c29b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE0MjQ0ODl9.uAF02964UOcqtKqTjOOPdR_aoNr0_iNJaX7WhdNqdw4

###
PUT http://localhost:8080/api/trucks/6304d9c097d4222e22b81fc1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjEyNjEzMDd9.ntsNW758iCgRKCG6_mFR22KtayKzMicK5cWmFj1Idps

{
  "type": "LARGE STRAIGHT",
      "dimensions": {
    "width": 700,
    "length": 350,
    "height": 200
  },
  "payload": 4000
}


###
DELETE  http://localhost:8080/api/trucks/6308cc548109e1c756a6b327
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE1MjA5MTZ9.BBfSCr1aCcgLR-k-n9hTSnvF9I5E0xRVE-gZGMBNtUE


###
POST http://localhost:8080/api/trucks/630f1c0dd41a9006c8629c95/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE1MjA5MTZ9.BBfSCr1aCcgLR-k-n9hTSnvF9I5E0xRVE-gZGMBNtUE


###
POST http://localhost:8080/api/loads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDYwNWRlZGFkNWYzYTVkMGFlZjMyMSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluX3NoaXBwZXJAZ21haWwuY29tIiwiaWF0IjoxNjYxOTM0Njc2fQ.ACVmAmhT8mw6Jgo1eYClZ-x1m12XR2WNNZiyuv_YEMw

{
  "name": "Moving boxes",
  "payload": 100,
  "pickupAddress": "Flat 25, 12/F, Acacia Building 150 Kennedy Road",
  "deliveryAddress": "Sr. Rodrigo Domínguez Av. Bellavista N° 185",
  "dimensions": {
    "width": 44,
    "length": 32,
    "height": 66
  }
}

###
GET http://localhost:8080/api/loads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDYwNWRlZGFkNWYzYTVkMGFlZjMyMSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluX3NoaXBwZXJAZ21haWwuY29tIiwiaWF0IjoxNjYxNDI3OTExfQ.TR5wMRfqWBBJ2Y1mYBOjenn3I2tY28cmd9Bh9O3rMwY


###
GET http://localhost:8080/api/loads/630760de1d3bff5bd485df73
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDM2ZjVhMThiYjZlMmFiYWE0NWQ3NSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluOTBAZ21haWwuY29tIiwiaWF0IjoxNjYxMTY5NTA1fQ.wZnhfujvXJVvLN9SLaT6DyxWanz5Rm010YzVBJ6gAvU

###
PUT http://localhost:8080/api/loads/63060619dad5f3a5d0aef32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDM2ZjVhMThiYjZlMmFiYWE0NWQ3NSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluOTBAZ21haWwuY29tIiwiaWF0IjoxNjYxMTY5NTA1fQ.wZnhfujvXJVvLN9SLaT6DyxWanz5Rm010YzVBJ6gAvU

{
  "name": "Moving something",
  "payload": 200,
  "pickupAddress": "Flat 25, 12/F, Acacia Building 150 Kennedy Road",
  "deliveryAddress": "Sr. Rodrigo Domínguez Av. Bellavista N° 185",
  "dimensions": {
    "width": 100,
    "length": 22,
    "height": 33
  }
}

###
DELETE http://localhost:8080/api/loads/63037be6cb30cf8f5540aa7f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDM2ZjVhMThiYjZlMmFiYWE0NWQ3NSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluOTBAZ21haWwuY29tIiwiaWF0IjoxNjYxMTY5NTA1fQ.wZnhfujvXJVvLN9SLaT6DyxWanz5Rm010YzVBJ6gAvU

###
POST http://localhost:8080/api/loads/630f23228d4513b4aa8187ff/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDYwNWRlZGFkNWYzYTVkMGFlZjMyMSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluX3NoaXBwZXJAZ21haWwuY29tIiwiaWF0IjoxNjYxOTM0Njc2fQ.ACVmAmhT8mw6Jgo1eYClZ-x1m12XR2WNNZiyuv_YEMw

###
GET http://localhost:8080/api/loads/6307515f799ddf2d61d6aa7f/shipping_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDM2ZjVhMThiYjZlMmFiYWE0NWQ3NSIsInJvbGUiOiJTSElQUEVSIiwiZW1haWwiOiJrYXRpcmluOTBAZ21haWwuY29tIiwiaWF0IjoxNjYxMTY5NTA1fQ.wZnhfujvXJVvLN9SLaT6DyxWanz5Rm010YzVBJ6gAvU

###
GET http://localhost:8080/api/loads/active
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE0MzUyNzR9.xRgxw_o-tACwhE81R4XWDQdNPoOAO9i1uRBLpYXYz1A

###
PATCH http://localhost:8080/api/loads/active/state
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDRkNWY3MTBhNzZlNDczMTQxMjM3MSIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE0MzUyNzR9.xRgxw_o-tACwhE81R4XWDQdNPoOAO9i1uRBLpYXYz1A


###
GET http://localhost:8080/api/weather
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDhlMmY5MWEyYjRhN2ZlNjM1MDIwNiIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImthdGlyaW45MEBnbWFpbC5jb20iLCJpYXQiOjE2NjE1MjY3ODZ9.pj9vo_qzHPRp6Zt_3-bqXHfwTI7FFKfNCvnTAsOnVgo

{
  "city": "Kyiv"
}